<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-24 at 12:17:55.
 */
class OrmTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Orm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        defined('ROOT') or define('ROOT', dirname(__DIR__).'/../');
        include_once(dirname(__DIR__).DIRECTORY_SEPARATOR.'orm.php');
        $this->object = new Orm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Orm::__callStatic
     * @todo   Implement test__callStatic().
     */
    public function test__callStatic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );

    }

    /**
     * @covers Orm::find_by
     * @todo   Implement testFind_by().
     */
    public function testFind_by()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Orm::find_all
     * @todo   Implement testFind_all().
     */
    public function testFind_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Orm::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        $this->assertEquals($this->object->init('a'), $this->object);
    }

    public function testPluralize(){
        $this->assertEquals($this->object->pluralize('user'), 'users');
        $this->assertEquals($this->object->pluralize('repository'), 'repositories');
    }
}
